#example source paths
ADI_EXAMPLE_SRC = .

#Sub libraries source paths
ADI_BOARD_SRC = ../../boards

#Include paths
ADI_C_SRC_INCL = ../..
ADI_BOARDS_INCL = ../../boards/
ADI_MOTHERBOARD_INCL = ../../boards/motherboards
ADI_DAUGHTERBOARD_INCL = ../../boards/daughterboards
ADI_DAUGHTERBOARD_ADRV9025_INCL = ../../boards/daughterboards/adrv9025/include
ADI_FPGA9025_INCL = ../../devices/fpga9025/public/include
ADI_FPGA9010_INCL = ../../devices/fpga9010/public/include
ADI_ADRV9025_INCL = ../../devices/adrv9025/public/include
ADI_AD9528_INCL = ../../devices/ad9528/public/include
ADI_COMMON_INCL = ../../common
ADI_COMMON_ERROR_INCL = ../../common/adi_error
ADI_COMMON_LOGGING_INCL = ../../common/adi_logging
ADI_COMMON_HAL_INCL = ../../common/adi_hal
ADI_PLATFORM_INCL = ../../platforms
ADI_PLATFORM_UTILS_INCL = ../../platforms/platform_utils

#LIBs to link
LIB_ADI_BOARDS = ../../boards/libadi_boards.a
LIB_ADI_MOTHERBOARDS = ../../boards/motherboards/libadi_motherboard.a
LIB_ADI_DAUGHTERBOARDS = ../../boards/daughterboards/libadi_daughterboard.a
LIB_ADI_ADRV9025_DEVICE = ../../devices/adrv9025/libadi_adrv9025.a
LIB_ADI_COMMON_DEVICE = ../../common/libadi_common.a
LIB_ADI_PLATFORM = ../../platforms/libadi_platform.a
LIB_ADI_ADS8PLATFORM = ../../platforms/ads8/libadi_ads8platform.a
LIB_ADI_ADS9PLATFORM = ../../platforms/ads9/libadi_ads9platform.a
LIB_ADI_FPGA9025 = ../../devices/fpga9025/libadi_fpga9025.a
LIB_ADI_FPGA9010 = ../../devices/fpga9010/libadi_fpga9010.a
LIB_ADI_AD9528 = ../../devices/ad9528/libadi_ad9528.a

CC = gcc
LD = gcc
ARFLAGS = -rv
CFLAGS = -Wall -Werror -Wchar-subscripts -Wshadow -DDEBUG=1 -DGTEST=1 -I$(ADI_C_SRC_INCL) -I$(ADI_ADRV9025_INCL) -I$(ADI_COMMON_INCL) -I$(ADI_COMMON_ERROR_INCL) -I$(ADI_COMMON_LOGGING_INCL) -I$(ADI_COMMON_HAL_INCL) -I$(ADI_PLATFORM_INCL) -I$(ADI_PLATFORM_UTILS_INCL) -I$(ADI_FPGA9025_INCL) -I$(ADI_FPGA9010_INCL) -I$(ADI_AD9528_INCL) -I$(ADI_BOARDS_INCL) -I$(ADI_MOTHERBOARD_INCL) -I$(ADI_DAUGHTERBOARD_INCL) -I$(ADI_DAUGHTERBOARD_ADRV9025_INCL) 

EXT = c
TARGET = main

SRC = $(wildcard $(ADI_EXAMPLE_SRC)/*.$(EXT))
OBJS = $(SRC:.$(EXT)=.o)
#All DEPS are built by adi_adrv9025_board_lib
DEPS = $(LIB_ADI_BOARDS) $(LIB_ADI_MOTHERBOARDS) $(LIB_ADI_DAUGHTERBOARDS) $(LIB_ADI_ADRV9025_DEVICE) $(LIB_ADI_COMMON_DEVICE) $(LIB_ADI_PLATFORM) $(LIB_ADI_ADS8PLATFORM) $(LIB_ADI_ADS9PLATFORM) $(LIB_ADI_FPGA9025) $(LIB_ADI_FPGA9010) $(LIB_ADI_AD9528)

all: adi_adrv9025_board_lib \
	$(TARGET)

$(TARGET): adi_adrv9025_board_lib $(OBJS)
	$(LD) -o $@ $(OBJS) $(DEPS) -lm

.$(EXT).o:
	$(CC) $(CFLAGS) -o $@ -c $<

adi_adrv9025_board_lib:
	$(MAKE) -C $(ADI_BOARD_SRC)
	
clean:
	$(MAKE) -C $(ADI_BOARD_SRC) clean
	rm -rf *.o
	rm -rf *.a
	rm main